[package]
name = "testlib-ffi"
version = "0.1.0"
authors = ["Algo-ryth-mix <mail.baier.raphael@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="testlib"
crate-type = ["staticlib","cdylib"]