name: build-action

on: 
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ~/pmm
          key: ${{ runner.os }}-pmmcache

      - name: install dependencies
        run: |
          sudo apt-get install -yqq cmake gcc g++ libgl1-mesa-dev libglfw3-dev build-essential libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev xserver-xorg xserver-xorg-core x11-apps x11-xserver-utils xvfb python3-pip

      - name: build
        run: |
          mkdir build && cd build && cmake -G "Unix Makefiles" ..
          cmake --build .

      - name: run test
        run: |
          chmod u+x tools/img_compare.py
          chmod u+x tools/img_diff.py
          chmod u+x tools/img_crop.py
          pip3 install poetry
          export PATH=/home/runner/.local/bin:$PATH
          xvfb-run ./build/tests --reporters=junit --out=results.xml
        
      - name: Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        # the action is useless on pull_request events
        # (it can not create check runs or pull request comments)
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "results.xml"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: results.xml
